import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <nav className="p-4 bg-gray-900 border-b border-gray-800 flex justify-center gap-6">
          <Link href="/" className="text-white font-bold hover:text-blue-400">
            ✅ To-Do List
          </Link>
          <Link href="/about" className="text-gray-300 hover:text-blue-400">
            👤 About
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
